// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIuwCOsrBQED97kx010DdFsYVyKETnKg',
    appId: '1:298238850001:web:be27539fc38330b968a6f0',
    messagingSenderId: '298238850001',
    projectId: 'notes-12345-flutter-project',
    authDomain: 'notes-12345-flutter-project.firebaseapp.com',
    storageBucket: 'notes-12345-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0zbK2K6H_V1qOv4G9IMJ4HgExP5NM4-U',
    appId: '1:298238850001:android:847057f3185b4e8568a6f0',
    messagingSenderId: '298238850001',
    projectId: 'notes-12345-flutter-project',
    storageBucket: 'notes-12345-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApY43QNV59gGtygL9eiDDGuf6MZ_GSAbU',
    appId: '1:298238850001:ios:26b34660aeec4b4868a6f0',
    messagingSenderId: '298238850001',
    projectId: 'notes-12345-flutter-project',
    storageBucket: 'notes-12345-flutter-project.appspot.com',
    iosClientId: '298238850001-8t45tmm4ef67ckifclp8apf8n7ndmli4.apps.googleusercontent.com',
    iosBundleId: 'com.goniyo.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApY43QNV59gGtygL9eiDDGuf6MZ_GSAbU',
    appId: '1:298238850001:ios:26b34660aeec4b4868a6f0',
    messagingSenderId: '298238850001',
    projectId: 'notes-12345-flutter-project',
    storageBucket: 'notes-12345-flutter-project.appspot.com',
    iosClientId: '298238850001-8t45tmm4ef67ckifclp8apf8n7ndmli4.apps.googleusercontent.com',
    iosBundleId: 'com.goniyo.notes',
  );
}
